export const ADD_LOG = 'ADD_LOG';
export const CLEAR_LOG = 'CLEAR_LOG';
export const WARNING_BEFORE_CLEAR_LOG = 'WARNING_BEFORE_CLEAR_LOG';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const INCREMENT = 'INCREMENT';